/*            PROJETO BRASILEIRÃO         */ 

/*            CRIANDO DATABASES        */
CREATE DATABASE BRASILEIRAO;
USE BRASILEIRAO;
/*---------------------------------------------------------------------------------------------------------------------- */
/*            CRIANDO TABLES        */

CREATE TABLE TIMES (
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(60),
    MASCOTE VARCHAR(25),
    FUNDACAO YEAR,
	ESTADIO VARCHAR(17),
    CIDADE VARCHAR(50),
    UF VARCHAR(2),
    TITULOS INT
);

CREATE TABLE JOGADORES (
    IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
    POSIÇÃO VARCHAR (30),
    NOME VARCHAR(60),
    IDADE VARCHAR(25),
    NCAMISA INT,
    ID_TIME int,
    FOREIGN KEY (ID_TIME)
    REFERENCES TIMES(IDTIME)
);

/*---------------------------------------------------------------------------------------------------------------------- */
/*            INSERINDO DADOS TIMES       */
INSERT INTO TIMES VALUES(NULL, 'INTERNACIONAL', 'SACI', '1909',  'BEIRA RIO', 'PORTO ALEGRE', 'RS','3');
INSERT INTO TIMES VALUES(NULL, 'ATLETICO MINEIRO', 'GALO', '1908', 'MRV ARENA','BELO HORIZONTE', 'BH', '3');
INSERT INTO TIMES VALUES(NULL, 'SAO PAULO', 'SANTO PAULO', '1930', 'MORUMBIS','SAO PAULO', 'SP', '6');
INSERT INTO TIMES VALUES(NULL, 'FLUMINENSE', 'CARTOLA','1902', 'MARACANA', 'RIO DE JANEIRO', 'RJ', '4');

/*---------------------------------------------------------------------------------------------------------------------- */
/*            INSERINDO DADOS JOGADORES      */
INSERT INTO JOGADORES VALUES(NULL, 'MEIA','ALAN PATRICK', '32', '10', 1); /*INTER*/
INSERT INTO JOGADORES VALUES(NULL,'GOLEIRO','SERGIO ROCHET', '31', '32', 1); /*INTER*/
INSERT INTO JOGADORES VALUES(NULL, 'ATACANTE','ENNER VALENCIA', '34', '13', 1); /*INTER*/

INSERT INTO JOGADORES VALUES(NULL,'ATACANTE','HULK', '37', '7', 2); /*ATLETICO MINEIRO*/
INSERT INTO JOGADORES VALUES(NULL,'MEIA','GUSTAVO SCARPA', '30', '6', 2); /*ATLETICO MINEIRO*/
INSERT INTO JOGADORES VALUES(NULL, 'ATACANTE','EDUARDO VARGAS', '34', '11', 2); /*ATLETICO MINEIRO*/

INSERT INTO JOGADORES VALUES(NULL,'MEIA','JAMES RODRIGUEZ', '32', '19', 3); /*SAO PAULO*/
INSERT INTO JOGADORES VALUES(NULL,'LAT DIREITO','RAFINHA', '38', '13', 3); /*SAO PAULO*/
INSERT INTO JOGADORES VALUES(NULL,'ATACANTE','CALLERI', '30', '9', 3); /*SAO PAULO*/

INSERT INTO JOGADORES VALUES(NULL,'MEIA', 'GANSO','34','10', 4); /*FLUMINENSE*/
INSERT INTO JOGADORES VALUES(NULL,'LAT ESQUERDO','MARCELO', '35', '12', 4); /*FLUMINENSE*/
INSERT INTO JOGADORES VALUES(NULL,'ATACANTE','KENO', '34', '11', 4); /*FLUMINENSE*/


/*---------------------------------------------------------------------------------------------------------------------- */
/*            REALIZANDO QUERYS      */
SELECT * FROM TIMES A    
INNER JOIN JOGADORES B
WHERE A.IDTIME = B.ID_TIME           /* MOSTRANDO OS REGISTROS EM ORDEM ALFABÉTICA */
ORDER BY A.NOME ASC;

SELECT * FROM TIMES A    
INNER JOIN JOGADORES B				  /* MOSTRANDO OS REGISTROS EM ORDEM QUE FOREM INSERIDOS */
WHERE A.IDTIME = B.ID_TIME;         


SELECT A.NOME, A.MASCOTE, A.FUNDACAO, A.ESTADIO, A.CIDADE, 
	   A.UF, A.TITULOS, 
       B.POSIÇÃO, B.NOME, B.IDADE, B.NCAMISA 
FROM TIMES A                                        /* MOSTRANDO OS REGISTROS DE APENAS UM TIME */
INNER JOIN JOGADORES B
WHERE A.IDTIME = B.ID_TIME AND A.NOME = 'INTERNACIONAL'; 


SELECT A.NOME, A.MASCOTE, A.FUNDACAO, A.ESTADIO, A.CIDADE, 
	   A.UF, A.TITULOS, 
       B.POSIÇÃO, B.NOME, B.IDADE, B.NCAMISA 
FROM TIMES A                                        /* MOSTRANDO OS REGISTROS DE APENAS UM TIME */
INNER JOIN JOGADORES B
WHERE A.IDTIME = B.ID_TIME AND A.NOME = 'FLUMINENSE'; 















































